/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SERVER_H_RPCGEN
#define _RPC_SERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	struct {
		u_int array_len;
		int *array_val;
	} array;
	float a;
};
typedef struct args args;

struct min_max {
	int min;
	int max;
};
typedef struct min_max min_max;

struct float_array {
	struct {
		u_int array_len;
		float *array_val;
	} array;
};
typedef struct float_array float_array;

#define SERVER_PROG 0x23451111
#define SERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AVERAGE 1
extern  float * average_1(args *, CLIENT *);
extern  float * average_1_svc(args *, struct svc_req *);
#define MIN_MAX 2
extern  min_max * min_max_1(args *, CLIENT *);
extern  min_max * min_max_1_svc(args *, struct svc_req *);
#define PRODUCT 3
extern  float_array * product_1(args *, CLIENT *);
extern  float_array * product_1_svc(args *, struct svc_req *);
extern int server_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AVERAGE 1
extern  float * average_1();
extern  float * average_1_svc();
#define MIN_MAX 2
extern  min_max * min_max_1();
extern  min_max * min_max_1_svc();
#define PRODUCT 3
extern  float_array * product_1();
extern  float_array * product_1_svc();
extern int server_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);
extern  bool_t xdr_min_max (XDR *, min_max*);
extern  bool_t xdr_float_array (XDR *, float_array*);

#else /* K&R C */
extern bool_t xdr_args ();
extern bool_t xdr_min_max ();
extern bool_t xdr_float_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SERVER_H_RPCGEN */
