/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_server.h"

bool_t
xdr_args (XDR *xdrs, args *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->array.array_val, (u_int *) &objp->array.array_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_min_max (XDR *xdrs, min_max *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_float_array (XDR *xdrs, float_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->array.array_val, (u_int *) &objp->array.array_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
